[nix]
channel = "stable-24_05"

[deployment]
deploymentTarget = "autoscale"
run = "node index.js"
build = "npx prisma generate"

[deployment.web]
port = 3000

[[ports]]
localPort = 3000
externalPort = 3000

[env]
NODE_ENV = "development"