[nix]
channel = "stable-24_05"

[deployment]
deploymentTarget = "autoscale"
run = "npx ts-node src/server.ts"
build = "npx prisma generate"

[[ports]]
localPort = 3001
externalPort = 80

[env]
NODE_ENV = "development"